// === src/lexer/TokenType.java ===
package lexer;

public enum TokenType {
    // Anahtar Kelimeler
    KEYWORD_TANIMLA, KEYWORD_TIPI, KEYWORD_BASLANGIC,
    KEYWORD_ISE, KEYWORD_DEĞİLSE, KEYWORD_BÖYLEYKEN,
    KEYWORD_TEKRAR, KEYWORD_FONKSIYON, KEYWORD_YAZDIR,
    KEYWORD_GIRDI_AL, KEYWORD_GERI_VER, KEYWORD_AYRIL,
    KEYWORD_SURDUR, KEYWORD_DENEYAP, KEYWORD_YAKALA,
    KEYWORD_FIRLAT, KEYWORD_EKLE, KEYWORD_KALIP,
    KEYWORD_DURUMSEC, KEYWORD_DURUM, KEYWORD_VARSAYILAN,
    KEYWORD_DOGRU, KEYWORD_YANLIS, KEYWORD_GIRDI_SOR,

    // Veri Tipleri
    DATA_TYPE_TAM, DATA_TYPE_ONDALIK, DATA_TYPE_KAYAN,
    DATA_TYPE_YAZI, DATA_TYPE_MANTIKAL,

    // Operatörler
    ASSIGN_OP, BIN_OP_ARTI, BIN_OP_EKSI, BIN_OP_CARPI,
    BIN_OP_BOLU, BIN_OP_MODULO, BIN_OP_US, COMP_OP_BUYUKTUR,
    COMP_OP_KUCUKTUR, COMP_OP_ESITTIR, COMP_OP_BUYUK_ESIT,
    COMP_OP_KUCUK_ESIT, COMP_OP_FARKLI, LOGIC_OP_VE,
    LOGIC_OP_VEYA, LOGIC_OP_DEGIL,

    // Ayraçlar
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, DOLLAR,

    // Literaller
    IDENT, INT_LIT, FLOAT_LIT, STRING_LITERAL, INPUT_PROMPT,

    // Diğer
    COMMENT, EOF, ERROR
}
